import Head from 'next/head'
import Image from 'next/image'
import Hero from '@/components/Hero'
import Slider from '@/components/Slider'
import { SliderData } from '@/components/SliderData'
import Instagram from '@/components/Instagram'

export default function Home() {
  return (
    <div>
      <Head>
        <title>CAPTUR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Capture Photography' message='A portrait is not made in the camera but on either side of it.'/>
      <Slider slides={SliderData}/>
      <Instagram />
    </div>
  );
}